---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/index/index.html
    type: html
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/90123/articles/207304/master/file/figures/index/index.html"
