---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 2
  grid_elements:
  - path: figures/NucOverlayBeforeDilate2/NucOverlayBeforeDilate.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/90123/articles/207304/master/file/figures/NucOverlayBeforeDilate2/NucOverlayBeforeDilate.png"
    folder_url: "/users/90123/articles/207304/master/folder/figures/NucOverlayBeforeDilate2"
  - path: figures/NucOverlayBeforeDilate2/NucOverlayAfterDilate.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/90123/articles/207304/master/file/figures/NucOverlayBeforeDilate2/NucOverlayAfterDilate.png"
    folder_url: "/users/90123/articles/207304/master/folder/figures/NucOverlayBeforeDilate2"